CREATE DATABASE NBA;
USE NBA;
CREATE TABLE RANKING (
TEAM_ID VARCHAR(15),
LEAGUE_ID VARCHAR(2),
SEASON_ID VARCHAR(6),
STANDINGSDATE DATE,
CONFERENCE VARCHAR(15),
TEAM VARCHAR(30),
G INT,
W INT,
L INT,
W_PCT FLOAT,
HOME_RECORD VARCHAR(10),
ROAD_RECORD VARCHAR(10));

